from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def patch(path: str, old: str, new: str, *, count: int = 1) -> None:
    target = ROOT / path
    text = target.read_text(encoding="utf-8")
    found = text.count(old)
    if found < count:
        raise RuntimeError(f"patch anchor missing in {path}: {old[:120]!r} ({found=})")
    target.write_text(text.replace(old, new, count), encoding="utf-8", newline="\n")


patch(
    "tests/test_gpu_backend_policy.py",
    '''def test_direct_runtime_rejects_legacy_seed_vc_after_blackwell_swap(tmp_path, monkeypatch):\n    monkeypatch.setattr(hardware.platform, "machine", lambda: "x86_64")\n    _write_setup(tmp_path, "cu128", seed_vc_backend="cu124")\n    monkeypatch.setattr(environment, "selected_nvidia_gpu", lambda: gpu("12.0"))\n    with pytest.raises(RuntimeError, match="Seed-VC was set up for cu124"):\n        environment.require_current_environment(tmp_path)\n''',
    '''def test_direct_runtime_only_blocks_seed_vc_after_blackwell_swap(tmp_path, monkeypatch):\n    monkeypatch.setattr(hardware.platform, "machine", lambda: "x86_64")\n    setup = _write_setup(tmp_path, "cu128", seed_vc_backend="cu124")\n    monkeypatch.setattr(environment, "selected_nvidia_gpu", lambda: gpu("12.0"))\n    assert environment.require_current_environment(tmp_path) == setup\n    with pytest.raises(RuntimeError, match="Seed-VC was set up for cu124"):\n        environment.require_current_environment(tmp_path, worker_name="seed_vc")\n''',
)

patch(
    "tests/test_gpu_runtime_compatibility.py",
    '''def test_runtime_hardware_blocks_stale_seed_vc_gpu_stack_on_blackwell(monkeypatch):\n    blackwell = _gpu(0, "12.0", name="Blackwell GPU")\n    monkeypatch.setattr(hardware.platform, "machine", lambda: "x86_64")\n    monkeypatch.setattr(env_contract, "selected_nvidia_gpu", lambda: blackwell)\n    status = env_contract.runtime_hardware_status(\n        {\n            "irodori_backend": "cu128",\n            "worker_backends": {"seed_vc": "cu124"},\n        }\n    )\n    assert status["ok"] is False\n    assert status["preferred_backend"] == "cu128"\n    assert status["preferred_seed_vc_backend"] == "cpu"\n    assert "Seed-VC" in status["error"]\n''',
    '''def test_runtime_hardware_blocks_only_stale_seed_vc_stack_on_blackwell(monkeypatch):\n    blackwell = _gpu(0, "12.0", name="Blackwell GPU")\n    monkeypatch.setattr(hardware.platform, "machine", lambda: "x86_64")\n    monkeypatch.setattr(env_contract, "selected_nvidia_gpu", lambda: blackwell)\n    setup = {\n        "irodori_backend": "cu128",\n        "worker_backends": {"seed_vc": "cu124"},\n    }\n    assert env_contract.runtime_hardware_status(setup)["ok"] is True\n    status = env_contract.runtime_hardware_status(setup, worker_name="seed_vc")\n    assert status["ok"] is False\n    assert status["preferred_backend"] == "cu128"\n    assert status["preferred_seed_vc_backend"] == "cpu"\n    assert "Seed-VC" in status["error"]\n''',
)

patch(
    "tests/test_seed_vc_pinned_assets.py",
    '    assert first["schema"] == 3\n',
    '    assert first["schema"] == 4\n',
)

patch(
    "tests/test_worker_result_contracts.py",
    '        lambda _root: {"irodori_backend": "cpu"},\n',
    '        lambda _root, **_kwargs: {"irodori_backend": "cpu"},\n',
    count=2,
)

# This test is generated by _ci_gpu_policy_hardening.py earlier in the same job.
# Isolate setup-state publication from the real Seed-VC asset contract and CUDA
# kernel preflight, both of which have dedicated coverage elsewhere.
patch(
    "tests/test_gpu_runtime_contract.py",
    '    monkeypatch.setattr(setup_env, "_validate_cuda_backend", lambda _backend: gpu)\n',
    '    monkeypatch.setattr(setup_env, "_validate_cuda_backend", lambda _backend: gpu)\n'
    '    monkeypatch.setattr(setup_env, "seed_vc_contract_digest", lambda _root: "0" * 64)\n'
    '    monkeypatch.setattr(\n'
    '        setup_env,\n'
    '        "run_cuda_preflight",\n'
    '        lambda *_args, **_kwargs: {"ok": True, "fixture": True},\n'
    '    )\n',
)

print("GPU policy test fixtures synchronized")
